forge "http://forge.puppetlabs.com"

mod "apt",
    :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "php",
    :git => "git://github.com/saz/puppet-php.git"

mod "nginx",
    :git => "git://github.com/davidwinter/puppet-nginx.git"

mod "percona",
    :git => "git://github.com/kasperisager/puppet-percona.git",
    :ref => "template-variables-fix"

mod "vcsrepo",
    :git => "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
